name: Docs
on: [push, pull_request, workflow_dispatch]
permissions:
    contents: write
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          sudo apt-get install libasound-dev portaudio19-dev libportaudio2 libportaudiocpp0
          python -m pip install --upgrade pip
          pip install setuptools wheel twine
          pip install sphinx sphinx_rtd_theme
          pip install -e .

      - name: Sphinx build
        run: |
          sphinx-apidoc -f -o doc src/pyaudioai
          sphinx-build doc _build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _build/
          force_orphan: true