name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [3.7, 3.8, 3.9]
      fail-fast: false

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - name: Install Tox and any other packages
        run: pip install tox

      - name: Install requirements
        run: |
          sudo apt-get install libasound-dev portaudio19-dev libportaudio2 libportaudiocpp0

      - name: Run Tox
        run: |
          export OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}
          tox -e py
